### PR TITLE
fix*: close the underlying client on Storage close()

### LINKED ISSUE #150: AWS_ERROR_THREAD_INSUFFICIENT_RESOURCE when opening too many storage instances
### Expected Behavior

_No response_

### Actual Behaviour

Since the introduction of per-tenant / per-namespace storage, the storage (and so the client) is instantiated too many times leading to thread exhaustion.

Linked to https://kestra-io.zendesk.com/agent/tickets/444

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #150

### CODE REVIEW

File: src/main/java/io/kestra/storage/s3/S3Storage.java [hunk 1]
```diff
@@ -454,4 +457,22 @@ private String getPath(String tenantId, URI uri) {
     private static URI createUri(String tenantId, String key) {
         return URI.create("kestra://%s".formatted(key).replace(tenantId + "/", ""));
     }
+
+    public void close() {
+        if (this.s3Client != null) {
+            try {
+                this.s3Client.close();
+            } catch (Exception e) {
+                LOG.warn("Failed to close GcsStorage", e);
```
Comment (brian-mulier-p) [inline src/main/java/io/kestra/storage/s3/S3Storage.java:466]:
```suggestion
                LOG.warn("Failed to close S3Storage", e);
```

File: src/main/java/io/kestra/storage/s3/S3Storage.java [hunk 2]
```diff
@@ -454,4 +457,22 @@ private String getPath(String tenantId, URI uri) {
...
+            }
+        }
+
+        if (this.s3AsyncClient != null) {
+            try {
+                this.s3AsyncClient.close();
+            } catch (Exception e) {
+                LOG.warn("Failed to close GcsStorage", e);
```
Comment (brian-mulier-p) [inline src/main/java/io/kestra/storage/s3/S3Storage.java:474]:
```suggestion
                LOG.warn("Failed to close S3Storage", e);
```

**Review by brian-mulier-p — APPROVED** [review]
LGTM but typo
